# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b9821d41c1b6c6412d4ccf26dd7aa96"
name = "Countdown Timer"
application_url = "https://nonsenatorial-nicholas-unobsequiously.ngrok-free.dev"
embedded = true

[access_scopes]
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://nonsenatorial-nicholas-unobsequiously.ngrok-free.dev/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[pos]
embedded = false
