api_version = "2026-01"

[[extensions]]
name = "Countdown Timer"
handle = "countdown-timer"
uid = "2d6e9a3f-aa62-633c-0ce3-390dc16527cea09b75b2"
type = "theme"

  [[extensions.targeting]]
  target = "section"
  block_category = "utilities"
